services:
  rpi:
    image: 10.10.60.250:5000/rpi_client:latest
    container_name: rpi
    # network_mode: host
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - /home/pi/Desktop/iris/db:/app/db
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/app/certs
      - ./robot_identity:/app/robot_identity
      - ./ota_manifests:/app/ota_manifests
      - ./bot_state:/app/current_firmwares
    restart: unless-stopped
    

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    network_mode: host
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
      - ./ros_logs:/logs
      - ./promtail-positions:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
