# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Scrape metrics from your Python exporter in rpi container
  - job_name: 'rpi_system'
    static_configs:
      - targets: ['rpi:8002']   # 'rpi' is the Docker Compose service name
